"""add to_dict method to wallet

Revision ID: 695f4785c78d
Revises: 
Create Date: 2025-08-14 14:56:45.186916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695f4785c78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('wallet_uuid_key'))
)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
