FROM python:3.10

WORKDIR /tests

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

CMD ["pytest", "/tests", "-v"]