version: '3.8'

services:

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d  mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_NAME: db
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes: []
    command: >
      sh -c "flask db upgrade && flask run -h 0.0.0.0 -p 5000"
volumes:
  pg_data: