version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d  mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_URL: postgresql://myuser:mypassword@db:5432/mydb
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes: []
    command: flask run


  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - app
      - db
volumes:
  pg_data: